name: Forge Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Setup Java 26
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '26'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Save Folder
        run: |
          New-Item `
            -ItemType Directory `
            -Path ".\saves" `
            -Force

      - name: Create McFolder
        run: |
          mkdir D:\McFolder
          
      - name: Restore Playit Data
        run: |
          if (Test-Path ".\saves\playit.zip") {

            Write-Host "===== PLAYIT SAVE FOUND ====="

            New-Item `
              -ItemType Directory `
              -Path "C:\ProgramData\playit_gg" `
              -Force

            Expand-Archive `
              -Path ".\saves\playit.zip" `
              -DestinationPath "C:\ProgramData\playit_gg" `
              -Force

            Write-Host "Playit restored!"
          }
          else {
            Write-Host "===== NO PLAYIT SAVE FOUND ====="
          }

      - name: Restore World Save
        run: |
          if (Test-Path ".\saves\world.zip") {
            Write-Host "===== WORLD SAVE FOUND ====="

            Expand-Archive `
              -Path ".\saves\world.zip" `
              -DestinationPath "D:\McFolder" `
              -Force

            Write-Host "World restored!"
          }
          else {
            Write-Host "===== NO WORLD SAVE FOUND ====="
          }

      - name: Download Forge Installer
        run: |
          Invoke-WebRequest `
            -Uri "https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.11-61.1.8/forge-1.21.11-61.1.8-installer.jar" `
            -OutFile "D:\McFolder\forge-installer.jar"

      - name: Install Forge Server
        run: |
          cd D:\McFolder
          java -jar forge-installer.jar --installServer

      - name: First Boot
        continue-on-error: true
        run: |
          cd D:\McFolder
          .\run.bat

      - name: Accept EULA
        run: |
          (Get-Content D:\McFolder\eula.txt) `
          -replace 'eula=false','eula=true' |
          Set-Content D:\McFolder\eula.txt

      - name: Generate Server Properties
        continue-on-error: true
        run: |
          Start-Process `
            -FilePath "D:\McFolder\run.bat" `
            -WorkingDirectory "D:\McFolder"

          Start-Sleep -Seconds 30

      - name: Set Online Mode False
        run: |
          (Get-Content D:\McFolder\server.properties) `
          -replace 'online-mode=true','online-mode=false' |
          Set-Content D:\McFolder\server.properties

      - name: Stop Minecraft
        continue-on-error: true
        run: |
          Get-Process java -ErrorAction SilentlyContinue |
          Stop-Process -Force

      - name: Set 12GB RAM
        run: |
          Set-Content D:\McFolder\user_jvm_args.txt "-Xms12G"
          Add-Content D:\McFolder\user_jvm_args.txt "-Xmx12G"

      - name: Start Server In Background
        run: |
          Start-Process `
            -FilePath "D:\McFolder\run.bat" `
            -WorkingDirectory "D:\McFolder"

          Start-Sleep -Seconds 30

      - name: Download Playit
        run: |
          Invoke-WebRequest `
            -Uri "https://builds.playit.gg/1.0.8/playit-windows-x86_64-signed.msi" `
            -OutFile "D:\playit.msi"

      - name: Install Playit
        run: |
          Start-Process msiexec.exe `
            -ArgumentList '/i D:\playit.msi /quiet /norestart' `
            -Wait

      - name: Start Playit
        run: |
          Start-Process `
            -FilePath "C:\Program Files\playit_gg\bin\playit.exe"

          Start-Sleep -Seconds 20

      - name: Generate Claim Code
        continue-on-error: true
        run: |
          & "C:\Program Files\playit_gg\bin\playit.exe" claim generate

      - name: Login URL
        continue-on-error: true
        run: |
          & "C:\Program Files\playit_gg\bin\playit.exe" account login-url

      - name: Setup Playit
        continue-on-error: true
        run: |
          & "C:\Program Files\playit_gg\bin\playit.exe" setup

      - name: Keep Server Alive
        run: |
          Start-Sleep -Seconds 90

      - name: Stop Minecraft
        continue-on-error: true
        run: |
          Get-Process java -ErrorAction SilentlyContinue |
          Stop-Process

      - name: Show Latest Log Before Shutdown
        continue-on-error: true
        run: |
          if (Test-Path "D:\McFolder\logs\latest.log") {
            Get-Content `
              "D:\McFolder\logs\latest.log" `
              -Tail 100
          }

      - name: Stop Playit
        continue-on-error: true
        run: |
          Get-Process playit* -ErrorAction SilentlyContinue |
          Stop-Process -Force

          Start-Sleep -Seconds 5

      - name: Compress World
        run: |
          Compress-Archive `
            -Path "D:\McFolder\world" `
            -DestinationPath ".\saves\world.zip" `
            -Force

      - name: Save Playit Data
        run: |
          New-Item `
            -ItemType Directory `
            -Path "D:\playit_backup" `
            -Force

          Copy-Item `
            "C:\ProgramData\playit_gg\playit.toml" `
            "D:\playit_backup\"

          Copy-Item `
            "C:\ProgramData\playit_gg\installed_user.sid" `
            "D:\playit_backup\"

          Compress-Archive `
            -Path "D:\playit_backup\*" `
            -DestinationPath ".\saves\playit.zip" `
            -Force

      - name: Commit Saves
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add saves/world.zip
          git add saves/playit.zip

          git commit -m "Update server data" || echo "Nothing to commit"

          git push
